[package]
name = "susanoo"
version = "0.0.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
hyper = "~0.11"
futures = "~0.1"
tokio-core = "~0.1"
regex = "~0.2"
typemap = "*"

[dev-dependencies]
r2d2 = "*"
r2d2_sqlite = "*"
rusqlite = "*"

[features]
unstable = []
